### ISSUE TITLE
liquid democracy demo for dapp-ideas workshop

### ISSUE THREAD

**Issue by dckc** [rchain-community/rgov#53]
@jimscarver did a demo recently (IOU links) but getting the final tally didn't work for what looks like a core dev issue:
 - [x] https://github.com/rchain/rchain/issues/3375 deploy fails without error message
   - @jimscarver worked with the core team to diagnose
 - [x] demo network #55 
 - [x] demo front end #56 
 - [x] land the `reorganize-actions` branch #45
 - [x] rehearsal (again, w/DC)
 - [x] demo on a Wednesday debrief (_though it didn't actually work_)
 - [x] [recorded demo](https://youtu.be/JC5RP7IeG5g)

**Comment by dckc** [comment]
For reference: **Ideation workshop** message Mon, Aug 3, 2020, 4:54 AM:

> Dear Dan,
>
> Congratulations. You came 3rd with Rv2020.
>
> You were voted by members in the ideation workshop and as a result you have come 3rd, and are entitled to a reward of ... . We will need you to demonstrate your idea on zoom call that we can record and invite members to attend. You can set your own criteria as to what constitutes a demo and it may incorporate your idea with additional collaborations (e.g. those on going for rchat and rvote). We know work is already underway on many of these ideas as part of very welcome wider collaboration within the coop. Your REV will be deposited the day after your demo zoom call.
> 
> The aim of the demo should ideally focus on two things. The idea in and of itself and it's current demonstrable state and its contribution to the RChain story. If you care to reach out to any members of the board we will help prepare and where we can contribute to the demo, so take your pick, you may pick more than one.
> 
> Take a little time to figure out when you would be happy to give the demo so that you can get board member support and pick a date and time that works for you no later than one month from today and let us know in a no more than one week from today when that date should be.
> 
> Well done on your efforts and we look forward to hearing from you.
>
> Best regards
>
> The RChain Board Of Directors

and:

 - [An ideation workshop for RChain Dapps](https://docs.google.com/document/d/1bg6k0IrV6BuyF4FowKODa-t9EO1BWphIeNugo3_FTjM/edit) Apr 2020

**Comment by jimscarver** [comment]
Steve Ross-Talbot <steve.pi4tech@gmail.com>
Mon, Aug 3, 2020, 5:53 AM
to me, BOD

Dear Jim,

Congratulations. You won.

You were voted by members in the ideation workshop and as a result you have come 1st, and are entitled to a reward of 100000. To collect the REV we will of course need your RChain address so that we can deposit your prize. We will need you to demonstrate your idea on zoom call that we can record and invite members to attend. You can set your own criteria as to what constitutes a demo and it may incorporate your idea with additional collaborations (e.g. those on going for rchat and rvote). We know work is already underway on many of these ideas as part of very welcome wider collaboration within the coop. Your REV will be deposited the day after your demo zoom call.

The aim of the demo should ideally focus on two things. The idea in and of itself and it's current demonstrable state and its contribution to the RChain story. If you care to reach out to any members of the board we will help prepare and where we can contribute to the demo, so take your pick, you may pick more than one.

Take a little time to figure out when you would be happy to give the demo so that you can get board member support and pick a date and time that works for you no later than one month from today and let us know in a no more than one week from today when that date should be.

Well done on your efforts and we look forward to hearing from you.

Best regards

The RChain Board Of Directors

**Comment by dckc** [comment]
@jimscarver writes:
> tally and delegate are working!  thanks @Bill Keuntje and @w2vy 

What was the fix? Are you saying https://github.com/rchain/rchain/issues/3375 wasn't a blocker after all?

> Can @GaryC and @Rao participate in the demo tomorrow?

here's hoping...

**Comment by jimscarver** [comment]
@tgrospic sent me a debug verion of rnode and the problem turned out to be trying to concatinate a uri and a string. Our test did not test a uri. oops.
```
2021-04-12 18:37:07,801 [DEBUG] [node-runner-85      ] [coop.rchain.rholang.stdout   ]- "end"
2021-04-12 18:37:07,832 [INFO ] [node-runner-85      ] [c.r.c.u.r.RuntimeManagerImpl ]- DEPLOY ERROR:
coop.rchain.rholang.interpreter.errors$OperatorNotDefined: Error: Operator `++` is not defined on Uri.
2021-04-12 18:37:07,833 [INFO ] [node-runner-85      ] [c.r.c.u.r.RuntimeManagerImpl ]- Refunding 04df5a50268de0c6f4f23ea146da35210da8a2ebbded4f132efc80768d9aa03bcc5fd07c70df6c8d1afb6aa9d0547223c4cdbfaf854776e3f5ebb684e9a1b38d0d with 0
2021-04-12 18:37:12,724 [INFO ] [node-runner-87      ] [.r.c.e.BlockRetriever$$anon$1]- Block 4c56e1f1a5... is not in RequestedBlocks.
```

**Comment by dckc** [comment]
Bill: rehearsal this weekend with @w2vy ?
DC: prefer Sat.
resolved: 11am ET / 10am CT Sat, provided @w2vy is available. Bill to check.

**Comment by dckc** [comment]
For reference: [2020-09-26 3:10PM KC time](https://discord.com/channels/375365542359465989/700696110980792381/759507283716603944):
> dckc:: FWIW, the next step on the rv2020 award is (from the board): "We will need you to demonstrate your idea ... and invite members to attend. You can set your own criteria as to what constitutes a demo ...". The current rv2020 "dust" design doesn't meet my (current) criteria. I don't intend to claim the award until I flesh out ocap-based voting, in particular https://github.com/rchain-community/liquid-democracy/pull/11 . for follow-up, see #identity-and-agency .

**Comment by dckc** [comment]
The workshop submission was [2020-04-21 5:32PM KC time](https://discord.com/channels/375365542359465989/700696110980792381/702285749688598570)

> 1. Short Title: rv2020 - rchain voting with discord integration
> 2. Short Description: Using discord OAuth integration, we can
>    "springboard" discord identities into on-chain RChain coop
>    membership voting rights, preserving a high degree of privacy.
> 3. Link: https://github.com/rchain-community/rv2020

**Comment by dckc** [comment]
bummer; it didn't quite work.

We owe a recording of it working. I plan to follow up on discord about times.

**Comment by jimscarver** [comment]
the issue we hit is fixed in
https://github.com/rchain-community/rgov/pull/102 awaiting @Bill Keuntje
***@***.***> s approval.

**Comment by dckc** [comment]
The [demo recording](https://youtu.be/JC5RP7IeG5g) completes this issue.
