### ISSUE TITLE
migrate TODOs (dashboard, ...) from participate.html to github issues list

### ISSUE THREAD

**Issue by dckc** [rchain-community/rgov#87]
Many of these have issues.

I started making sure they all do, but a dashboard is not a goal of mine, so rather than open an issue for it, I'm enumerating these here and letting anyone who cares about them advance them. After a time, we can close this issue and any that remain can stay in the someday pile.

  - [x] #86  show avatars for members; give emoji kudos <a href="https://emojipedia.org/red-heart/">❤️</a>
  - [x] #78 Groups and group operations with membership nick-names, not URIs for inboxes 
  - [x] #76 collect result history below current result
  - [x] #129 make retuned rholang executabl in result area
  - [x] #116 Governance user interface with dashboard -- part of UI/UX
  - [x] #132 Working group (multi-sig actions)
  - [x] #74 Ballots (multi-issue)
  - [x] #130 Crowd fund budgeting
  - [x] #21 Integration with github issues (graphql)
  - [x] #61 Ranked choice voting
  - [x] #116 Handle multiple deploys concurrently -- part of UI/UX
  - [x] #85 "insert 25cents to play" account rather than in-your-face signature at each move
  - [x] #131 Push more of the actions down into deployed contracts
  - [x] #39 Provide access to #define bindings in actions

cc @jimscarver @Bill-Keuntje

**Comment by dckc** [comment]
@jimscarver @Bill-Keuntje it looks like you guys are using project cards as lightweight TODO tracking; maybe that's a better place for some of these?

**Comment by Bill-Keuntje** [comment]
@dckc @jimscarver
I suggest that this issue be closed, as all of the unchecked boxes seem like larger discussions that deserve their own issues....

**Comment by dckc** [comment]
While they might merit their own issues, the idea was to leave this open until they have them.

I did a quick pass to see whether I care much about any that have not been promoted to their own issues, and I find an odd one:

 - #116 Handle multiple deploys concurrently -- part of UI/UX

What does multiple concurrent deploys have to do with a ballot demo? Now I wonder about the rest of the items in the list. I'm not inclined to close this until I find time to review.

**Comment by Bill-Keuntje** [comment]
#116 is the result of https://github.com/rchain-community/rgov/projects/3 which includes #85. 
However, I am OK with promoting "Handle multiple deploys concurrently" to an issue by itself and closing this checklist.
Issues created for the remaining TODO items: #133, #132, #131, #130, #129

**Comment by dckc** [comment]
Thanks
